project:
  type: website
  output-dir: docs

# Meta
description-meta: "Diadromy group website"
author-meta: "Jeffery C.F. Chan"

website:
  title: "Jeffery C.F. Chan"
  image: ""
  description: "Diadromy group website"
  search: false
 
  navbar:
    background: transparent #"#215a6e"  # You can change the background color here
    right: 
      - text: Home
        href: index.qmd    
      - text: About
        href: about.qmd
      - text: Research
        href: Research.qmd
      - text: Publications
        href: publications.qmd
      - text: Outreach
        href: outreach.qmd
      - text: Contact
        href: contact.qmd  

  
  #page-navigation: true
  
  page-footer: 
    right: "Built with {{< iconify fa-brands r-project >}} and [quarto](https://github.com/drganghe/quarto-academic-website-template)"
    left: "Jeffery C.F. Chan &copy; <script>document.write(new Date().getFullYear())</script>" 
  
  #reader-mode: true

  #draft-mode: unlinked
  
  #repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  #open-graph: true
  
  #twitter-card: true 
#  card-style: summary      
  
  #site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  #google-analytics:
    #tracking-id: ""  # Please delete or replace with your own tracking ID
    #anonymize-ip: true 

#bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    #link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    #include-in-header: "files/includes/_academic.qmd"

